name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies for Windows
      if: matrix.os == 'windows-latest'
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install ninja
    - name: Install dependencies for Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev
    - name: Install latest nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      run: cargo build --manifest-path multi_pong/Cargo.toml --release --verbose -Z unstable-options --out-dir artifacts --no-default-features --features "vulkan no-slow-safety-checks"
    - name: Copy Assets and Config(Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: cp -R ${{ github.workspace }}/multi_pong/assets ${{ github.workspace }}/artifacts ; cp -R ${{ github.workspace }}/multi_pong/config ${{ github.workspace }}/artifacts
    - name: Copy Assets and Config(Windows)
      if: matrix.os == 'windows-latest'
      run: xcopy /E /I ${{ github.workspace }}\multi_pong\assets ${{ github.workspace }}\artifacts\assets; xcopy /E /I ${{ github.workspace }}\multi_pong\config ${{ github.workspace }}\artifacts\config
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
            ${{ github.workspace }}/artifacts
            !${{ github.workspace }}/artifacts/**/*.pdb
        name: ${{ matrix.os }}-${{ github.run_number }}
